import type { Sprite } from '../sprite'

/*
 * Móveis e decorações da loja, desenhados para o quarto. Cada um tem o próprio tamanho; o quarto decide onde
 * fica. Arte original do GasmTask.
 */

const INK = '#1a1c2c'
const WOOD = '#c98a4b'
const WOOD_DARK = '#a0612e'

export const FURNITURE: Record<string, Sprite> = {
  mug_coffee: {
    rows: ['..g..g..', '...g..g.', 'kkkkkk..', 'kcccck..', 'kwwwwkkk', 'kwrrwk.k', 'kwwwwkkk', '.kkkk...'],
    palette: { k: INK, g: '#c2cddb', c: '#5a3a29', w: '#f4f4f4', r: '#b13e53' },
  },
  plant_small: {
    rows: [
      '.....k....',
      '....kgk...',
      '.k..kgk.k.',
      'kgk.kGkkgk',
      'kggkkGkggk',
      '.kggkGggk.',
      '..kkggGkk.',
      '.kkkkkkkk.',
      '.kOOOOOOk.',
      '..kooook..',
      '..kooook..',
      '...kkkk...',
    ],
    palette: { k: INK, g: '#38b764', G: '#a7f070', o: '#ef7d57', O: '#b4693a' },
  },
  poster_space: {
    rows: [
      'kkkkkkkkkkkk',
      'knnnnnnnnwnk',
      'knwnnnnnnnnk',
      'knnnnmmnnnnk',
      'knnnmppmnnnk',
      'knnmpPPpmnnk',
      'knnmpPPpmnwk',
      'knnnmppmnnnk',
      'knnnnmmnnnnk',
      'knnnnnnnnnnk',
      'knwnnnnyynnk',
      'knnnnnyYYynk',
      'knnnnnnyynnk',
      'knnnnnnnnwnk',
      'knnnnnnnnnnk',
      'kkkkkkkkkkkk',
    ],
    palette: { k: INK, n: '#29366f', w: '#f4f4f4', m: '#8d5ad1', p: '#e8558e', P: '#ffd1e3', y: '#73eff7', Y: '#41a6f6' },
  },
  lamp_desk: {
    rows: ['..kkkk..', '.kyyyyk.', 'kyyyyyyk', 'kkkkkkkk', '...kgk..', '...kgk..', '...kgk..', '..kkgkk.', '.kggggk.', '.kkkkkk.'],
    palette: { k: INK, y: '#ffcd75', g: '#566c86' },
  },
  desk_simple: {
    rows: [
      'kkkkkkkkkkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwwwwwwwwwk',
      'kWWWWWWWWWWWWWWWWWWWWk',
      'kkkkkkkkkkkkkkkkkkkkkk',
      '.kWk..........kwwwwwk.',
      '.kWk..........kwwyywk.',
      '.kWk..........kwwwwwk.',
      '.kWk..........kkkkkkk.',
      '.kWk..........kwwwwwk.',
      '.kWk..........kwwyywk.',
      '.kWk..........kwwwwwk.',
      '.kWk..........kkkkkkk.',
      '.kWk..............kWk.',
      '.kkk..............kkk.',
    ],
    palette: { k: INK, w: WOOD, W: WOOD_DARK, y: '#ffcd75' },
  },
  rug_round: {
    rows: [
      '........kkkkkkkkkkkkkkkk........',
      '....kkkkrrrrrrrrrrrrrrrrkkkk....',
      '..kkrrrryyyyyyyyyyyyyyyyrrrrkk..',
      '.krrryyyyrrrrrrrrrrrrrryyyyrrrk.',
      '.krrryyyyrrrrrrrrrrrrrryyyyrrrk.',
      '..kkrrrryyyyyyyyyyyyyyyyrrrrkk..',
      '....kkkkrrrrrrrrrrrrrrrrkkkk....',
      '........kkkkkkkkkkkkkkkk........',
    ],
    palette: { k: INK, r: '#e8558e', y: '#ffcd75' },
  },
  beanbag_purple: {
    rows: [
      '....kkkkkkkk....',
      '..kkmmmmmmmmkk..',
      '.kmmmmmmmmmmmmk.',
      '.kmwmmmmmmmmmmk.',
      'kmwmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmMk',
      'kmmmmMMMMMmmmmMk',
      'kmmmMMMMMMMmmmMk',
      'kMmmmmmmmmmmMMMk',
      '.kMMmmmmmmmmMMk.',
      '..kkMMMMMMMMkk..',
      '....kkkkkkkk....',
    ],
    palette: { k: INK, m: '#8d5ad1', M: '#5d3a9b', w: '#c9a8f0' },
  },
  bookshelf_wood: {
    rows: [
      'kkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkk',
      'kWrr..g...p.Wk',
      'kWrrbbg...p.Wk',
      'kWrrbbg.yyp.Wk',
      'kWrrbbg.yyp.Wk',
      'kWrrbbg.yyp.Wk',
      'kWrrbbg.yyp.Wk',
      'kWWWWWWWWWWWWk',
      'kWb......gg.Wk',
      'kWbb.p...gg.Wk',
      'kWbbyp...ggrWk',
      'kWbbyp.z.ggrWk',
      'kWbbypzzzggrWk',
      'kWbbyp.z.ggrWk',
      'kWWWWWWWWWWWWk',
      'kW...GG.....Wk',
      'kW..GGGG....Wk',
      'kW...GG..yy.Wk',
      'kW..kkkk.yy.Wk',
      'kW..kook.rr.Wk',
      'kW..kook.rr.Wk',
      'kWWWWWWWWWWWWk',
      'kkkkkkkkkkkkkk',
      '.kk........kk.',
    ],
    palette: {
      k: INK,
      w: WOOD,
      W: WOOD_DARK,
      r: '#b13e53',
      b: '#3b5dc9',
      g: '#38b764',
      G: '#a7f070',
      y: '#ffcd75',
      p: '#e8558e',
      z: '#f4f4f4',
      o: '#ef7d57',
    },
  },
  neon_sign: {
    rows: [
      'kkkkkkkkkkkkkkkkkkkkk',
      'knnnnnnnnnnnnnnnnnnnk',
      'knnpppnpppnpppnpppnnk',
      'knnpnnnpnpnpnnnpnpnnk',
      'knnppnnpnpnpnnnpnpnnk',
      'knnpnnnpnpnpnnnpnpnnk',
      'knnpnnnpppnpppnpppnnk',
      'knnnnnnnnnnnnnnnnnnnk',
      'kkkkkkkkkkkkkkkkkkkkk',
    ],
    palette: { k: INK, n: '#333c57', p: '#ff7ac6' },
  },
  bed_cozy: {
    rows: [
      'kkkk........................',
      'kwwk........................',
      'kwwk........................',
      'kwwk........................',
      'kwwkkkkkkk..................',
      'kwwkkzzzzk..................',
      'kwwkkzzzzkkkkkkkkkkkkkkkkkkk',
      'kwwkkzzzzkbbbbbbbbbbbbbbbbbk',
      'kwwkkkkkkkbBbbbBbbbBbbbBbbbk',
      'kwwkssssssbbbbbbbbbbbbbbbbbk',
      'kwwkkkkkkkkkkkkkkkkkkkkkkkkk',
      'kwwkWWWWWWWWWWWWWWWWWWWWWWWk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      '.kWk....................kWk.',
      '.kkk....................kkk.',
    ],
    palette: { k: INK, w: WOOD, W: WOOD_DARK, z: '#f4f4f4', s: '#dfe6fb', b: '#3b5dc9', B: '#41a6f6' },
  },
  chair_gamer: {
    rows: [
      '..kkkkkkkk..',
      '..krrrrrrk..',
      '..krkkkkrk..',
      '..krkrrkrk..',
      '..krkrrkrk..',
      '..krkkkkrk..',
      '..krrrrrrk..',
      '..krrrrrrk..',
      'kkkrrrrrrkkk',
      'kgkkkkkkkkgk',
      'kgkrrrrrrkgk',
      'kkkkkkkkkkkk',
      '.....kk.....',
      '..kkkkkkkk..',
      '.k...kk...k.',
      'kk........kk',
    ],
    palette: { k: INK, r: '#b13e53', g: '#566c86' },
  },
  aquarium_small: {
    rows: [
      'kkkkkkkkkkkkkk',
      'kaaaaaaaaaaaak',
      'kAAAAAAAAAAAAk',
      'kAAoAAAAAAAzAk',
      'kAooOAAAAAAAAk',
      'kAAoAAAAAyAAAk',
      'kAAAAAAAyyYAAk',
      'kAgAAgAAAyAAAk',
      'kgggssgggssggk',
      'kkkkkkkkkkkkkk',
    ],
    palette: { k: INK, a: '#73eff7', A: '#41a6f6', o: '#ef7d57', O: '#b13e53', y: '#ffcd75', Y: '#e8a33d', z: '#f4f4f4', g: '#38b764', s: '#ffe08a' },
  },
}
